### ISSUE TITLE
Windows x64 LuaFileSystem dll crash

### ISSUE THREAD

**Issue by matiasah** [luapower/lfs#1]
Hello, I installed all the dynamic libraries of LuaFileSystem from LuaPower to get file system support on love2d 0.9.2 (Which runs LuaJIT 2.0.3). The library loads properly on Windows x64 but then I use lfs.dir and it crashes on the second iteration. I don't really know what causes this, perhaps I could be using the wrong build for this, but I'm just letting you know that this happens.

**Comment by capr** [comment]
Hi, do you have a small code snippet that I could try? Thanks.

**Comment by matiasah** [comment]
Yeah, we're using this code over here.
https://github.com/Starkkz/play2d/blob/master/game/commands.lua

In my opinion, it could be failing because love2d was compiled on msvc. (I couldn't find this statement anywhere but I think it is) as the LuaFileSystem developer said that the program that runs it must be compiled in the same software as the dynamic library. If this was the case it would be nice to have msvc builds on this git, right? I mean, for future developers.

**Comment by capr** [comment]
Yes, you have to build the entire stack with the same compiler and luapower only supports mingw-w64 for Windows on x64[1]. Can you test with the luapower's luajit binary and see if it still crashes?

About supporting msvc, that would mean writing build scripts and keeping binaries for all luapower packages for both win32 and win64, which is a lot of boring work. I'd rather bring in useful cocos2d modules to luapower so that those modules can be used outside of any framework. Sorry but I don't like frameworks, that's why I made luapower :)

[1] https://luapower.com/building

**Comment by matiasah** [comment]
Hey, I don't think it's necessary to do further tests to see if it crashes. I just noticed that love2d runs a lua51.dll (I assume this was built using msvc). I could try replacing that with mingw builds and that should just fix it. I should be able to use LuaFileSystem on my program.

Does LuaPower have already compiled binaries for LuaJIT? I just wonder this because I was looking for compiled binaries and I couldn't find them.

Edit: I found it here https://luapower.com/files/luapower/bin/mingw64/
I tested it but now "print" doesn't work, and for some reason it still crashes when using LuaFileSystem.

Edit (2): Er, luajit-2.1.0-alpha. Is there any available LuaJIT binary compatible with this compilation of LuaFileSystem? A friend was running the LuaJIT 2.0.3 on the same program (But on Linux) and it seems to work fine for him.

**Comment by capr** [comment]
All luapower packages come with binaries for all 3 desktop platforms both 32bit and 64bit.

You mean you just downloaded the luajit binary from that link and print doesn't work? What exactly are you trying to mix there? :) 

Btw, that binary is luajit-2.1. Go to http://luapower.com/luajit for package info.

**Comment by matiasah** [comment]
I meant that the LuaJIT binary I used from there works because it runs the actual code, however "print" doesn't print and LuaFileSystem still crashes at the same part. Could it because I still need to use a MinGW program rather than a MSVC program? This time the LuaJIT dll was the MinGW built you shared there, I was expecting both things to work fine together.

**Comment by capr** [comment]
yes, everything needs to be built with either mingw or msvc.

**Comment by matiasah** [comment]
Hey, once again we did another test. The 32 bit version of LuaFileSystem (MinGW) works on the 32 bit version of lua51.dll (compiled under MSVC) in a 32 bit MSVC program. But the 64 bit version crashes on the 64 bit version of lua51.dll in the same 64 bit MSVC program. I don't think that really makes sense, but anyways it looks like we're going to stick to 32 bit stuff.
